name: Parallel Pipelines

on:
  push:
    branches:
      - staging


jobs:
  pipeline_one:
    name: Pipeline One
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Pipeline One
        run: echo "Step 1 in Pipeline One"

      - name: Step 2 in Pipeline One
        run: echo "Step 2 in Pipeline One"

  pipeline_two:
    name: Pipeline Two
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Pipeline Two
        run: echo "Step 1 in Pipeline Two"

      - name: Step 2 in Pipeline Two
        run: echo "Step 2 in Pipeline Two"
